// Generated by CoffeeScript 1.9.3
var expect, jsdom, solve;

solve = require('../tasks/task-1');

expect = require('chai').expect;

jsdom = require('mocha-jsdom');

describe('Task 2 tests', function() {
  var htmlTemplate;
  htmlTemplate = '<ul id="list"></ul>';
  jsdom();
  beforeEach(function() {
    return document.body.innerHTML = htmlTemplate;
  });
  return describe('Valid', function() {
    return it('expect to add 5 inputs with labels for them', function() {
      var func;
      return func = solve();
    });
  });
});
